=== AtB-AS/planner-web/orgs/schema-validation.json
{
  "$ref": "#/definitions/OrgData",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "definitions": {
    "OrgData": {
      "additionalProperties": false,
      "properties": {
        "fylkeskommune": {
          "additionalProperties": false,
          "properties": {
            "logoSrc": {
              "type": "string"
            },
            "logoSrcDark": {
              "type": "string"
            },
            "name": {
              "type": "string"
            }
          },
          "required": ["name", "logoSrc", "logoSrcDark"],
          "type": "object"
        },
        "featureConfig": {
          "type": "object",
          "properties": {
            "replaceTitleWithLogoInHeader": {
              "type": "boolean"
            },
            "forceTheme": {
              "type": "string",
              "enum": ["light", "dark"]
            },
            "enableShowTripPatternPrice": {
              "type": "boolean"
            }
          },
          "required": ["enableShowTripPatternPrice"]
        },
        "orgId": {
          "enum": ["atb", "fram", "nfk", "vkt", "farte"],
          "type": "string"
        },
        "authorityId": {
          "type": "string"
        },
        "$schema": {
          "type": "string"
        },
        "supportEmail": {
          "type": "string"
        },
        "urls": {
          "additionalProperties": false,
          "properties": {
            "accessibilityStatementUrl": {
              "$ref": "#/definitions/TranslatableUrl"
            },
            "facebookLink": {
              "type": "string"
            },
            "instagramLink": {
              "type": "string"
            },
            "privacyDeclarationUrl": {
              "$ref": "#/definitions/TranslatableUrl"
            },
            "supportUrl": {
              "$ref": "#/definitions/TranslatableUrl"
            },
            "helpUrl": {
              "$ref": "#/definitions/TranslatableUrl"
            },
            "twitterLink": {
              "type": "string"
            },
            "homePageUrl": {
              "properties": {
                "name": {
                  "type": "string"
                },
                "href": {
                  "type": "string"
                }
              }
            },
            "purchaseTicketUrl": {
              "$ref": "#/definitions/TranslatableUrl"
            },
            "androidAppUrl": {
              "$ref": "#/definitions/TranslatableUrl"
            },
            "iosAppUrl": {
              "$ref": "#/definitions/TranslatableUrl"
            },
            "ticketInfoUrl": {
              "$ref": "#/definitions/TranslatableUrl"
            },
            "sitemapUrls": {
              "dev": {
                "name": {
                  "type": "string"
                }
              },
              "staging": {
                "name": {
                  "type": "string"
                }
              },
              "prod": {
                "name": {
                  "type": "string"
                }
              }
            }
          },
          "required": [
            "privacyDeclarationUrl",
            "accessibilityStatementUrl",
            "supportUrl"
          ],
          "type": "object"
        },
        "journeyApiConfigurations": {
          "additionalProperties": false,
          "properties": {
            "waitReluctance": {
              "type": "number"
            },
            "walkingReluctance": {
              "type": "number"
            },
            "transferPenalty": {
              "type": "number"
            },
            "defaultTransferSlack": {
              "type": "number"
            }
          },
          "type": "object"
        },
        "embed": {
          "additionalProperties": false,
          "properties": {
            "allowedOrigins": {
              "items": {
                "type": "string"
              },
              "type": "array"
            }
          },
          "required": ["allowedOrigins"],
          "type": "object"
        },
        "appLinks": {
          "additionalProperties": false,
          "properties": {
            "dev": { "$ref": "#/definitions/AppLinks" },
            "staging": { "$ref": "#/definitions/AppLinks" },
            "prod": { "$ref": "#/definitions/AppLinks" }
          },
          "type": "object"
        }
      },
      "required": ["featureConfig", "orgId", "supportEmail", "urls"],
      "type": "object"
    },
    "TranslatableUrl": {
      "additionalProperties": false,
      "properties": {
        "default": {
          "type": "string"
        },
        "en-US": {
          "type": "string"
        },
        "no": {
          "type": "string"
        },
        "nn": {
          "type": "string"
        }
      },
      "required": ["default"],
      "type": "object"
    },
    "AppLinks": {
      "additionalProperties": false,
      "properties": {
        "iosAppIds": {
          "items": { "type": "string" },
          "type": "array"
        },
        "androidApps": {
          "items": {
            "additionalProperties": false,
            "properties": {
              "packageName": { "type": "string" },
              "sha256CertFingerprints": {
                "items": { "type": "string" },
                "type": "array"
              }
            },
            "required": ["packageName", "sha256CertFingerprints"],
            "type": "object"
          },
          "type": "array"
        }
      },
      "required": ["iosAppIds", "androidApps"],
      "type": "object"
    }
  }
}

=== AtB-AS/planner-web/orgs/vkt.json
{
  "$schema": "./schema-validation.json",

  "orgId": "vkt",
  "authorityId": "VKT:Authority:VKT_ID",

  "supportEmail": "post@vkt.no",

  "fylkeskommune": {
    "logoSrc": "/vestfold_fylkeskommune.svg",
    "logoSrcDark": "/vestfold_fylkeskommune.svg",
    "name": "Vestfold fylkeskommune"
  },

  "featureConfig": {
    "enableShowTripPatternPrice": false,
    "forceTheme": "light"
  },

  "urls": {
    "privacyDeclarationUrl": {
      "default": "https://www.vkt.no/vilkaar-og-personvern/personvern/"
    },

    "accessibilityStatementUrl": {
      "default": "https://www.vkt.no/om-oss/tilgjengelighetserklaering/"
    },

    "supportUrl": {
      "default": "https://www.vkt.no/om-oss/kontakt-oss/",
      "en-US": "https://www.vkt.no/english/"
    },
    "homePageUrl": {
      "name": "vkt.no",
      "href": "https://vkt.no"
    },
    "ticketInfoUrl": {
      "en-US": "https://www.vkt.no/english/",
      "nn": "https://www.vkt.no/reise/billetter-og-priser/",
      "default": "https://www.vkt.no/reise/billetter-og-priser/"
    },
    "purchaseTicketUrl": {
      "en-US": "https://www.vkt.no/english/",
      "nn": "https://www.vkt.no/reise/billetter-og-priser/",
      "default": "https://www.vkt.no/reise/billetter-og-priser/"
    },
    "sitemapUrls": {
      "dev": "http://localhost:3000",
      "staging": "https://vkt-staging.planner-web.mittatb.no/",
      "prod": "https://reise.vkt.no/"
    },
    "androidAppUrl": {
      "default": "https://play.google.com/store/apps/details?id=no.vfk.travelassistant"
    },
    "iosAppUrl": {
      "default": "https://apps.apple.com/no/app/vkt/id6673909689"
    }
  },
  "journeyApiConfigurations": {
    "waitReluctance": 1.0,
    "walkingReluctance": 4.0,
    "transferPenalty": 0,
    "defaultTransferSlack": 0
  },
  "embed": {
    "allowedOrigins": ["https://vkt.no", "https://*.vkt.no"]
  }
}

=== AtB-AS/planner-web/orgs/fram.json
{
  "$schema": "./schema-validation.json",

  "orgId": "fram",
  "authorityId": "MOR:Authority:MOR",

  "supportEmail": "fram@mrfylke.no",

  "fylkeskommune": {
    "logoSrc": "/fram_mor_fylkeskommune.svg",
    "logoSrcDark": "/fram_mor_fylkeskommune_dark.svg",
    "name": "Møre og Romsdal fylkeskommune"
  },

  "featureConfig": {
    "replaceTitleWithLogoInHeader": true,
    "enableShowTripPatternPrice": true,
    "disableBoatComboPriceSearch": false
  },

  "urls": {
    "privacyDeclarationUrl": {
      "default": "https://frammr.no/personvern"
    },

    "accessibilityStatementUrl": {
      "default": "https://uustatus.no/nb/erklaringer/publisert/7d09e41a-8b28-4bc9-b5d2-a6bc8432f2cf"
    },

    "supportUrl": {
      "default": "https://reise.frammr.no/contact",
      "en-US": "https://reise.frammr.no/contact"
    },
    "homePageUrl": {
      "name": "frammr.no",
      "href": "https://www.frammr.no/"
    },
    "ticketInfoUrl": {
      "en-US": "https://frammr.no/billettar/billettar-og-prisar/?sprak=3",
      "nn": "https://frammr.no/billettar/billettar-og-prisar/?sprak=11",
      "default": "https://frammr.no/billettar/billettar-og-prisar/"
    },
    "purchaseTicketUrl": {
      "en-US": "https://frammr.no/tickets/how-to-buy-a-ticket/?sprak=3",
      "nn": "https://frammr.no/billettar/slik-kjoper-du-billett/",
      "default": "https://frammr.no/billettar/slik-kjoper-du-billett/"
    },
    "sitemapUrls": {
      "dev": "http://localhost:3000",
      "staging": "https://fram-staging.planner-web.mittatb.no/",
      "prod": "https://reise.frammr.no/"
    },
    "androidAppUrl": {
      "default": "https://play.google.com/store/apps/details?id=no.mrfylke.fram.production"
    },
    "iosAppUrl": {
      "default": "https://apps.apple.com/no/app/fram/id6447612651"
    }
  },
  "journeyApiConfigurations": {
    "waitReluctance": 1.0,
    "walkingReluctance": 4.0,
    "transferPenalty": 0,
    "defaultTransferSlack": 120
  },
  "embed": {
    "allowedOrigins": ["https://frammr.no", "https://*.frammr.no"]
  }
}

=== AtB-AS/planner-web/orgs/farte.json
{
  "$schema": "./schema-validation.json",

  "orgId": "farte",
  "authorityId": "TEL:Authority:TFK_ID",

  "supportEmail": "farte@telemarkfylke.no ",

  "fylkeskommune": {
    "logoSrc": "/telemark_fylkeskommune.svg",
    "logoSrcDark": "/telemark_fylkeskommune.svg",
    "name": "Telemark fylkeskommune"
  },

  "featureConfig": {
    "forceTheme": "light",
    "enableShowTripPatternPrice": false
  },

  "urls": {
    "privacyDeclarationUrl": {
      "default": "https://www.farte.no/vilkaar-og-personvern/"
    },

    "accessibilityStatementUrl": {
      "default": "https://www.farte.no/om-farte/tilgjengelighetserklaering/"
    },

    "supportUrl": {
      "default": "https://www.farte.no/kundeservice/",
      "en-US": "https://www.farte.no/english/"
    },
    "homePageUrl": {
      "name": "farte.no",
      "href": "https://www.farte.no/"
    },
    "ticketInfoUrl": {
      "en-US": "https://www.farte.no/english/",
      "nn": "https://www.farte.no/reise/billetter-og-priser/",
      "default": "https://www.farte.no/reise/billetter-og-priser/"
    },
    "purchaseTicketUrl": {
      "en-US": "https://www.farte.no/english/",
      "nn": "https://www.farte.no/reise/billetter-og-priser/",
      "default": "https://www.farte.no/reise/billetter-og-priser/"
    },
    "sitemapUrls": {
      "dev": "http://localhost:3000",
      "staging": "https://farte-staging.planner-web.mittatb.no/",
      "prod": "https://reise.farte.no/"
    },
    "androidAppUrl": {
      "default": "https://play.google.com/store/apps/details?id=no.tfk.travelassistant"
    },
    "iosAppUrl": {
      "default": "https://apps.apple.com/no/app/farte/id6479402566"
    }
  },
  "journeyApiConfigurations": {
    "waitReluctance": 1.0,
    "walkingReluctance": 4.0,
    "transferPenalty": 0,
    "defaultTransferSlack": 0
  },
  "embed": {
    "allowedOrigins": ["https://farte.no", "https://*.farte.no"]
  }
}

=== AtB-AS/planner-web/orgs/nfk.json
{
  "$schema": "./schema-validation.json",
  "orgId": "nfk",
  "authorityId": "NOR:Authority:12",

  "supportEmail": "sentrumsterminalen@boreal.no",

  "fylkeskommune": {
    "logoSrc": "/nfk_fylkeskommune.svg",
    "logoSrcDark": "/nfk_fylkeskommune_dark.svg",
    "name": "Nordland fylkeskommune"
  },

  "featureConfig": {
    "enableShowTripPatternPrice": true,
    "disableBoatComboPriceSearch": false
  },

  "urls": {
    "privacyDeclarationUrl": {
      "default": "https://www.reisnordland.no/personvern-og-cookies"
    },

    "accessibilityStatementUrl": {
      "default": "https://uustatus.no/nb/erklaringer/publisert/ae5bc315-272a-469e-b4cb-8ba5164ea988"
    },

    "supportUrl": {
      "default": "https://www.reisnordland.no/kontaktskjema",
      "en-US": "https://www.reisnordland.com/contact-us"
    },

    "instagramLink": "https://www.instagram.com/reisnordland",
    "facebookLink": "https://www.facebook.com/ReisNordland",
    "homePageUrl": {
      "name": "reisnordland.no",
      "href": "https://www.reisnordland.no/"
    },
    "ticketInfoUrl": {
      "en-US": "https://www.reisnordland.no/priser-pa-buss",
      "no": "https://www.reisnordland.no/priser-pa-buss",
      "default": "https://www.reisnordland.no/priser-pa-buss"
    },
    "purchaseTicketUrl": {
      "en-US": "https://www.reisnordland.no/kjop-bussbillett",
      "no": "https://www.reisnordland.no/kjop-bussbillett",
      "default": "https://www.reisnordland.no/kjop-bussbillett"
    },
    "sitemapUrls": {
      "dev": "http://localhost:3000",
      "staging": "https://nfk-staging.planner-web.mittatb.no/",
      "prod": "https://reise.reisnordland.no/"
    },
    "androidAppUrl": {
      "default": "https://play.google.com/store/apps/details?id=no.reisnordland.reis.production"
    },
    "iosAppUrl": {
      "default": "https://apps.apple.com/no/app/reis/id1574137854"
    }
  },
  "journeyApiConfigurations": {
    "waitReluctance": 1.0,
    "walkingReluctance": 4.0,
    "transferPenalty": 0,
    "defaultTransferSlack": 0
  },
  "embed": {
    "allowedOrigins": ["https://reisnordland.no", "https://*.reisnordland.no"]
  },
  "appLinks": {
    "staging": {
      "iosAppIds": [
        "7U3L7LAA9V.no.reisnordland.reis.staging",
        "7U3L7LAA9V.no.reisnordland.reis.debug"
      ],
      "androidApps": [
        {
          "packageName": "no.reisnordland.reis.staging",
          "sha256CertFingerprints": [
            "3E:3F:5B:F0:C1:BD:3B:C9:2B:32:6A:48:D1:65:11:4D:BD:9E:F2:D1:35:F4:46:1F:00:E4:7E:D6:9F:7D:88:BD"
          ]
        },
        {
          "packageName": "no.reisnordland.reis.debug",
          "sha256CertFingerprints": [
            "FA:C6:17:45:DC:09:03:78:6F:B9:ED:E6:2A:96:2B:39:9F:73:48:F0:BB:6F:89:9B:83:32:66:75:91:03:3B:9C"
          ]
        }
      ]
    }
  }
}

=== AtB-AS/planner-web/orgs/atb.json
{
  "$schema": "./schema-validation.json",
  "orgId": "atb",
  "authorityId": "ATB:Authority:2",

  "supportEmail": "kundeservice@atb.no",

  "fylkeskommune": {
    "logoSrc": "/trl_fylkeskommune.svg",
    "logoSrcDark": "/trl_fylkeskommune_dark.svg",
    "name": "Trøndelag fylkeskommune"
  },

  "featureConfig": {
    "enableShowTripPatternPrice": true,
    "disableBoatComboPriceSearch": true
  },

  "urls": {
    "privacyDeclarationUrl": {
      "default": "https://www.atb.no/vilkar/personvernerklaering-for-kundetjenester/"
    },

    "accessibilityStatementUrl": {
      "default": "https://uustatus.no/nb/erklaringer/publisert/2eb632a6-8e02-4d83-bdc3-3d9901f079bd"
    },

    "supportUrl": {
      "default": "https://atb.no/kundeservice/",
      "en-US": "https://www.atb.no/en/customer-service/"
    },
    "facebookLink": "https://www.facebook.com/atb.no/",
    "instagramLink": "https://www.instagram.com/atb_no/",
    "twitterLink": "https://twitter.com/atb_no",
    "homePageUrl": {
      "name": "atb.no",
      "href": "https://atb.no/"
    },
    "ticketInfoUrl": {
      "en-US": "https://www.atb.no/en/fares/",
      "no": "https://www.atb.no/priser/",
      "default": "https://www.atb.no/priser/"
    },
    "sitemapUrls": {
      "dev": "http://localhost:3000",
      "staging": "https://atb-staging.planner-web.mittatb.no/",
      "prod": "https://reise.atb.no/"
    },
    "purchaseTicketUrl": {
      "en-US": "https://www.atb.no/en/ticket/",
      "no": "https://www.atb.no/billett/",
      "default": "https://www.atb.no/billett/"
    },
    "androidAppUrl": {
      "default": "https://play.google.com/store/apps/details?id=no.mittatb.store"
    },
    "iosAppUrl": {
      "default": "https://apps.apple.com/us/app/atb/id1502395251"
    }
  },
  "journeyApiConfigurations": {
    "waitReluctance": 1.0,
    "walkingReluctance": 4.0,
    "transferPenalty": 0,
    "defaultTransferSlack": 120
  },
  "appLinks": {
    "staging": {
      "iosAppIds": [
        "CSV447Q97L.no.mittatb.staging",
        "CSV447Q97L.no.mittatb.debug"
      ],
      "androidApps": [
        {
          "packageName": "no.mittatb.staging",
          "sha256CertFingerprints": [
            "B1:41:B6:A9:A2:42:18:1A:68:96:45:15:F1:E9:86:F6:A1:D2:09:AF:7A:DD:BA:B2:B2:25:CA:5A:DD:C3:5F:B4"
          ]
        },
        {
          "packageName": "no.mittatb.debug",
          "sha256CertFingerprints": [
            "FA:C6:17:45:DC:09:03:78:6F:B9:ED:E6:2A:96:2B:39:9F:73:48:F0:BB:6F:89:9B:83:32:66:75:91:03:3B:9C"
          ]
        }
      ]
    }
  }
}
